development:
  github:
    client_id: "3dedabee17eb5c2c04e3"
    client_secret: "79776ff2937d275763bdd6937509d552f5904e12"
  google:
    client_id: "319099194810-ak8ij2j0hlfcs507ikc77qt92nf01u7e.apps.googleusercontent.com" 
    client_secret: "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"
test:
  github:
    client_id: ""
    client_secret: ""
  google:
    client_id: "" 
    client_secret: ""